import os
from pathlib import Path

TEMPLATES = {
    "flask-app": {
        "name": "Flask Web App",
        "files": {
            "src/app.py": '''from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/")
def home():
    return jsonify({"message": "Hello from Sycronix!", "status": "running"})

@app.route("/health")
def health():
    return jsonify({"status": "healthy"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
''',
            "src/config.py": '''import os

SECRET_KEY = os.getenv("SECRET_KEY", "dev-key-change-in-production")
DEBUG = os.getenv("DEBUG", "true").lower() == "true"
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "5000"))
''',
            "requirements.txt": "flask>=3.0\npython-dotenv>=1.0\n",
            ".env.example": "SECRET_KEY=change-me\nDEBUG=true\nPORT=5000\n",
            "README.md": "# Flask App\n\nGenerated by Sycronix Dev Agent\n\n## Run\n\n```bash\npip install -r requirements.txt\npython src/app.py\n```\n",
        },
        "post_install": "pip install flask python-dotenv",
        "run_command": "cd {project_dir} && python src/app.py",
    },
    "fastapi-backend": {
        "name": "FastAPI Backend",
        "files": {
            "app/main.py": '''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Sycronix API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def root():
    return {"service": "Sycronix API", "version": "1.0.0"}

@app.get("/health")
def health():
    return {"status": "healthy"}
''',
            "app/models.py": '''"""Data models for the API."""
from pydantic import BaseModel
from typing import Optional

class Item(BaseModel):
    id: Optional[int] = None
    name: str
    description: Optional[str] = None
''',
            "app/config.py": '''import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./data.db")
DEBUG = os.getenv("DEBUG", "true").lower() == "true"
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "8000"))
''',
            "requirements.txt": "fastapi>=0.100\nuvicorn>=0.23\npydantic>=2.0\n",
            ".env.example": "DEBUG=true\nPORT=8000\nDATABASE_URL=sqlite:///./data.db\n",
            "README.md": "# FastAPI Backend\n\nGenerated by Sycronix Dev Agent\n\n## Run\n\n```bash\npip install -r requirements.txt\nuvicorn app.main:app --reload\n```\n",
        },
        "post_install": "pip install fastapi uvicorn pydantic",
        "run_command": "cd {project_dir} && uvicorn app.main:app --reload --host 0.0.0.0",
    },
    "python-cli": {
        "name": "Python CLI Tool",
        "files": {
            "src/main.py": '''#!/usr/bin/env python3
"""CLI tool generated by Sycronix."""
import argparse

def main():
    parser = argparse.ArgumentParser(description="Sycronix CLI Tool")
    parser.add_argument("--name", "-n", default="World", help="Name to greet")
    args = parser.parse_args()
    print(f"Hello, {args.name}!")

if __name__ == "__main__":
    main()
''',
            "src/utils.py": '''"""Utility functions."""
import os
import json

def load_config(path: str = "config.json") -> dict:
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}
''',
            "setup.py": '''from setuptools import setup, find_packages

setup(
    name="sycronix-cli",
    version="0.1.0",
    packages=find_packages("src"),
    package_dir={"": "src"},
    entry_points={"console_scripts": ["sycronix-cli=main:main"]},
)
''',
            "requirements.txt": "click>=8.0\n",
            "README.md": "# Python CLI\n\nGenerated by Sycronix Dev Agent\n\n## Install\n\n```bash\npip install -e .\n```\n",
        },
        "post_install": "pip install click",
        "run_command": "cd {project_dir} && python src/main.py --help",
    },
    "html-portfolio": {
        "name": "HTML/CSS Portfolio",
        "files": {
            "index.html": '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio | Sycronix</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <nav>
            <h1>Portfolio</h1>
            <ul>
                <li><a href="#about">About</a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section id="hero">
            <h2>Hello, I'm <span class="highlight">Developer</span></h2>
            <p>Full-stack developer & problem solver</p>
        </section>
        <section id="about">
            <h2>About</h2>
            <p>Building things with code.</p>
        </section>
        <section id="projects">
            <h2>Projects</h2>
            <div class="project-grid">
                <div class="project-card">
                    <h3>Project 1</h3>
                    <p>Description</p>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <p>&copy; 2026. Built with Sycronix.</p>
    </footer>
</body>
</html>
''',
            "style.css": '''* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0f1a; color: #e2e8f0; line-height: 1.6; }
header { background: #111827; padding: 1rem 2rem; border-bottom: 1px solid #1e293b; }
nav { display: flex; justify-content: space-between; align-items: center; max-width: 1200px; margin: 0 auto; }
nav h1 { color: #00d4ff; }
nav ul { list-style: none; display: flex; gap: 2rem; }
nav a { color: #6b7280; text-decoration: none; }
nav a:hover { color: #00d4ff; }
.highlight { color: #00d4ff; }
#hero { text-align: center; padding: 6rem 2rem; }
#hero h2 { font-size: 3rem; margin-bottom: 1rem; }
#hero p { color: #6b7280; font-size: 1.2rem; }
section { max-width: 1200px; margin: 0 auto; padding: 4rem 2rem; }
h2 { color: #f8fafc; margin-bottom: 2rem; font-size: 2rem; }
.project-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; }
.project-card { background: #111827; border: 1px solid #1e293b; border-radius: 8px; padding: 1.5rem; }
.project-card h3 { color: #00d4ff; margin-bottom: 0.5rem; }
.project-card p { color: #6b7280; }
footer { text-align: center; padding: 2rem; color: #6b7280; border-top: 1px solid #1e293b; }
''',
            "README.md": "# Portfolio\n\nGenerated by Sycronix Dev Agent\n\nOpen `index.html` in your browser.\n",
        },
        "post_install": "",
        "run_command": "cd {project_dir} && python -m http.server 8080",
    },
}


class Scaffolder:
    def __init__(self, output_dir: str = None):
        self.output_dir = Path(output_dir or os.getcwd())

    def list_templates(self) -> list:
        return list(TEMPLATES.keys())

    def get_template_info(self, name: str) -> dict:
        template = TEMPLATES.get(name)
        if not template:
            return None
        return {
            "name": template["name"],
            "files": list(template["files"].keys()),
            "post_install": template["post_install"],
        }

    def scaffold(self, template_name: str, project_name: str = None) -> dict:
        template = TEMPLATES.get(template_name)
        if not template:
            return {"success": False, "error": f"Unknown template: {template_name}"}

        project_name = project_name or template_name
        project_dir = self.output_dir / project_name

        if project_dir.exists():
            return {"success": False, "error": f"Directory {project_dir} already exists"}

        project_dir.mkdir(parents=True, exist_ok=True)

        created_files = []
        for filepath, content in template["files"].items():
            full_path = project_dir / filepath
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)
            created_files.append(str(full_path))

        return {
            "success": True,
            "project_dir": str(project_dir),
            "files": created_files,
            "post_install": template["post_install"],
            "run_command": template["run_command"].format(project_dir=str(project_dir)),
        }
