import asyncio
import os
from pathlib import Path


class Executor:
    def __init__(self, work_dir: str = None):
        self.work_dir = work_dir or os.getcwd()

    async def run_command(self, command: str, timeout: int = 120) -> dict:
        try:
            process = await asyncio.create_subprocess_shell(
                command,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=self.work_dir,
            )
            stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=timeout)
            return {
                "success": process.returncode == 0,
                "stdout": stdout.decode() if stdout else "",
                "stderr": stderr.decode() if stderr else "",
                "exit_code": process.returncode,
            }
        except asyncio.TimeoutError:
            return {
                "success": False,
                "stdout": "",
                "stderr": f"Command timed out after {timeout}s",
                "exit_code": -1,
            }
        except Exception as e:
            return {
                "success": False,
                "stdout": "",
                "stderr": str(e),
                "exit_code": -1,
            }

    async def create_file(self, filepath: str, content: str = "") -> dict:
        try:
            full_path = Path(self.work_dir) / filepath if not os.path.isabs(filepath) else Path(filepath)
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)
            return {"success": True, "stdout": f"Created {full_path}", "stderr": "", "exit_code": 0}
        except Exception as e:
            return {"success": False, "stdout": "", "stderr": str(e), "exit_code": -1}

    async def install(self, package_spec: str) -> dict:
        if package_spec.startswith("pip"):
            return await self.run_command(package_spec)
        elif package_spec.startswith("npm"):
            return await self.run_command(package_spec)
        else:
            return await self.run_command(f"pip install {package_spec}")

    async def execute_step(self, step: dict) -> dict:
        step_type = step.get("type", "run_command")
        target = step.get("target", "")

        if step_type == "run_command":
            return await self.run_command(target)
        elif step_type == "create_file":
            filepath = target
            content = step.get("content", self._get_file_template(filepath))
            return await self.create_file(filepath, content)
        elif step_type == "modify_file":
            return await self.run_command(f"echo 'Modification requested for {target}'")
        elif step_type == "install":
            return await self.install(target)
        elif step_type == "configure":
            return await self.run_command(target)
        else:
            return await self.run_command(target)

    def _get_file_template(self, filepath: str) -> str:
        name = Path(filepath).stem
        if filepath.endswith("app.py"):
            return '''from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return {"message": "Hello from Sycronix!"}

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
'''
        elif "main.py" in filepath and "fastapi" in filepath.lower():
            return '''from fastapi import FastAPI
app = FastAPI(title="Sycronix API")

@app.get("/")
def root():
    return {"message": "Hello from Sycronix!"}

@app.get("/health")
def health():
    return {"status": "ok"}
'''
        elif filepath.endswith("requirements.txt"):
            return "flask>=3.0\n"
        elif filepath.endswith("README.md"):
            return f"# {name}\n\nGenerated by Sycronix Dev Agent\n"
        elif filepath.endswith(".py"):
            return f'"""Module: {name}"""\n\n\ndef main():\n    pass\n\n\nif __name__ == "__main__":\n    main()\n'
        elif filepath.endswith("setup.py"):
            return f'''from setuptools import setup, find_packages
setup(
    name="{name}",
    version="0.1.0",
    packages=find_packages(),
)
'''
        else:
            return f"# {name}\n"
